### ISSUE TITLE
Todo App 요구사항 명세서

### ISSUE THREAD

**Issue by j6d9s** [j6d9s/todo-app#2]
### 만들고자 하는 기능

todo 생성 , 조회, 업데이트, 삭제 기능

### 해야 할일

1. [ ] api 명세서 작성
2. [ ] 테이블 스키마 작성
3. [ ] rest api CRUD 구현

### 예상 작업 시간

3h
